version: '3'

services:
  mysql-local:
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/docker-entrypoint-initdb.d/:ro
    env_file:
      - .env.local
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    environment:
      - ./Djava.library.path=./DynamoDBLocal_lib
    ports:
      - "8000:8000"
    volumes:
      - ./data:/home/dynamodblocal/data/:rw
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "./data"]
  corrections:
    depends_on:
      - "dynamodb-local"
      - "mysql-local"
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    env_file:
      - .env.local
